[Feat] mistakeFeed 페이지 구현
coding-union-kr/siltarae-fe pull request #48
Opened 2023-12-15 12:54 UTC by cottonpup

## PR내용

- mistakeFeed 페이지 구현

## 연관이슈

Close #35 

## ✅ 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] 실행시 console 창에 에러나 경고가 없는것을 확인하였는가?
- [x] 해당 PR과 관련없는 변경사항이 없는가? (만약 있다면 이외 사항에 기술)

### 👉 이외 사항

2023-12-17 11:01 UTC, seovee requested changes
충돌 해결하고 머지해야할 것 같아요.

2023-12-17 11:01 UTC, seovee commented on components/AddPostButton.tsx
> +      className="fixed translate-x-48 translate-y-32 h-12 w-12  flex justify-center items-center rounded-full bg-white shadow-md hover:scale-[1.1]"
람쥐님 이거 버튼은 제꺼랑 충돌 해결하고 푸쉬해야할 것 같아요!

2023-12-17 11:01 UTC, seovee commented on components/ContentCard.tsx
> +}: ContentCardProps) {
오 이 부분좀 보고 참고하겠습니다. 
역시 타입스크립트 고수

2023-12-17 11:01 UTC, seovee commented on components/ContentCard.tsx
> +        <Link href="/">댓글 {comments} 개</Link>
여기는 나중에 개수는 어떻게 구현하실 건가요? 
length? 이런걸로 해야되겠죠???

2023-12-17 11:01 UTC, seovee commented on tailwind.config.ts
> +        secondary: "#856E69",
오 이 방법으로 메인컬러 빼놓는 것도 좋겠네요!

2023-12-18 05:10 UTC, cottonpup commented on components/ContentCard.tsx
> +        <Link href="/">댓글 {comments} 개</Link>
백엔드에서 받을거에여!

2023-12-18 05:18 UTC, seovee approved these changes

2023-12-18 05:19 UTC, merged