[Feat] myPage 구현
coding-union-kr/siltarae-fe pull request #49
Opened 2023-12-15 12:56 UTC by cottonpup

## PR내용

- myPage 구현

## 연관이슈

Close #36 

## ✅ 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] 실행시 console 창에 에러나 경고가 없는것을 확인하였는가?
- [x] 해당 PR과 관련없는 변경사항이 없는가? (만약 있다면 이외 사항에 기술)

### 👉 이외 사항

2023-12-17 11:05 UTC, seovee requested changes
이것도 충돌만 해결한 뒤 머지하면 될 것 같습니다.

2023-12-17 11:05 UTC, seovee commented on components/AddPostButton.tsx
>      >
요기 버튼도 충돌해결 해야겠네요!

2023-12-18 01:40 UTC, wade3420 approved these changes
사소한 리뷰 몇개 남겼습니다!

2023-12-18 01:40 UTC, wade3420 commented on components/Avatar.tsx
>            // eslint-disable-next-line @next/next/no-img-element
next/Image 는 사용안하시는걸까요?
https://nextjs.org/docs/messages/no-img-element

사용하기가 불편하거나 적절하지 않다라고 생각하시면 린트를 disable 해도 괜찮을 것 같아요! 

```
eslintrc.json
{
  // ...
  "rules": {
    // Other rules
    "@next/next/no-img-element": "off"
  }
}
```

2023-12-18 01:40 UTC, wade3420 commented on components/ContentCard.tsx
> +interface ContentCardProps {
👍

2023-12-18 01:40 UTC, wade3420 commented on pages/mistakeFeed/index.tsx
> +        <button
최신순 인기순 버튼들을 컴포넌트로 나눠도 좋을 것 같아요

2023-12-18 05:22 UTC, seovee approved these changes

2023-12-18 05:22 UTC, merged