[Feat] 댓글 api 기능 연결
coding-union-kr/siltarae-fe pull request #85
Opened 2023-12-29 07:20 UTC by seovee

## PR내용
- 댓글 api 기능 연결 완료 #69 
- https://github.com/coding-union-kr/siltarae-fe/issues/82
- https://github.com/coding-union-kr/siltarae-fe/issues/83
- https://github.com/coding-union-kr/siltarae-fe/issues/84

### Axios와 React Query로 댓글 조회, 추가, 삭제 기능을 구현해봤습니다. <br> 이렇게 사용하는 것이 맞는지 코드검토 부탁드립니다.

## 연관이슈

Close #69 #82 #83 #84 

## ✅ 체크리스트

- [x] Merge 하는 브랜치가 올바른가?
- [x] 코딩컨벤션을 준수하는가?
- [x] 실행시 console 창에 에러나 경고가 없는것을 확인하였는가?
- [x] 해당 PR과 관련없는 변경사항이 없는가? (만약 있다면 이외 사항에 기술)

### 👉 이외 사항

2023-12-29 07:24 UTC, cottonpup commented
수고하셨어요!! 👍 토큰값만 아래와 같이 env 값으로 변경해주세요!! 
https://github.com/coding-union-kr/siltarae-fe/blob/develop/api/mistakeApi.ts

2023-12-29 07:25 UTC, cottonpup requested changes
수고하셨어요!! 👍 토큰값만 아래와 같이 env 값으로 변경해주세요!!
https://github.com/coding-union-kr/siltarae-fe/blob/develop/api/mistakeApi.ts

2023-12-29 07:39 UTC, seovee commented
> 수고하셨어요!! 👍 토큰값만 아래와 같이 env 값으로 변경해주세요!! https://github.com/coding-union-kr/siltarae-fe/blob/develop/api/mistakeApi.ts

완료했습니다!

2023-12-29 07:41 UTC, cottonpup approved these changes

2023-12-30 12:16 UTC, wade3420 approved these changes
리뷰가 늦어서 죄송합니다 ㅠㅠ 늦은 만큼 많은 리뷰를 드리고 싶지만 프로젝트에 가장 깊게 고민하고 계신 분은 서비님이라 생각하여 세세한 리뷰보다는 저는 이렇게 쓴다 정도로 코멘트 드리고싶어요!

> Axios와 React Query로 댓글 조회, 추가, 삭제 기능을 구현해봤습니다.
이렇게 사용하는 것이 맞는지 코드검토 부탁드립니다.
> 
1. Axios 사용에 관하여
- Axios 타입 추론 
axios get post put delete 와 같은 함수는 제네릭 타입으로 response 타입을 주입해줄수 있습니다. 서버에서 받아오는 타입들을 axios 함수에서 정의해주는게 좋을 것 같아요
- Axios 인스턴스
    - axios의 장점 중 하나는 Axios interceptors 를 이용해서 요청 보내기전에 수행로직 (login token을 header에 넣는 로직 등) 을 일괄적으로 하거나 응답을 인터셉터하여 에러에 대한 처리를 할 수 있는 것이라고 생각합니다. 저는 리퀘스트에 로그인 토큰 넣는 것과 리스폰스에 에러를 throw하는 것 정도 로직을 interceptors 해주는 편이에요!
    
     https://axios-http.com/kr/docs/interceptors
    
2. 컴포넌트에서 직접 useQuery를 호출해서 다루기 보다는 아래 로직들은 useCreateComment 와 같은 훅으로 분리해서 비지니스로직을 분리하면 코드관리가 수월할 것 같아요. ( 조회나 삭제부분도 동일합니다!)

```
  const { mutate, isPending, isError, error, isSuccess } = useMutation({
    mutationFn: () => createComments(id as string, content),
    onSuccess: () => {
      setContent("");
    },
    onSettled: () => {
      // 자동으로 리프레쉬 되도록 해주는 코드
      queryCilent.invalidateQueries();
    },
  });

```

3. 저는 Suspense 를 이용해서 선언적으로 loading 처리를 하는 것을 좋아하는 편입니다 isloading 과 같은 분기 처리에서 해방될 수 있거든요!


수고하셨습니다 앞으로 종종 리뷰 요청해주시면 늦더라도 의견 달겠습니다!

2023-12-30 12:16 UTC, wade3420 commented on components/Comment.tsx
> +    mutationFn: (commentId: number) => deleteComments(commentId),
mutationFn 에 deleteComments 함수자체를 넣어서 사용해도 될것 같아요!

2023-12-30 12:16 UTC, wade3420 commented on components/CommentInput.tsx
> +    mutationFn: () => createComments(id as string, content),
여기서도 deleteComments처럼 mutate 하는 시점에서 id와 content를 mutate 함수에서 넣어주면 될것같은데 어떻게 생각하시나요?

2023-12-30 12:16 UTC, wade3420 commented on components/CommentInput.tsx
> +    onSettled: () => {
onSettled 에서  queryCilent.invalidateQueries() 를 해주는 이유가 있을까요? 저는 항상 onSuccess 에서 해와서요!

2023-12-30 12:16 UTC, wade3420 commented on components/Comment.tsx
> +      {isPending && (
여기서는 isPending을 사용하시는 이유가 있을까요?

2023-12-30 12:16 UTC, wade3420 commented on components/Comment.tsx
> +  const queryCilent = useQueryClient();
오타가 있네용 `queryClient`

2023-12-30 12:16 UTC, wade3420 commented on api/commentApi.ts
> +    const response = await api.get("/comment", {
```suggestion
    const response = await api.get<{comments : CommentDataType[]}>("/comment", {
```
axios 에 타입을 지정해주면 뒤에서 타입 단언을 안해주어도 될 것 같아요

2024-01-04 07:33 UTC, merged